fb_android_library(
  name = 'adinterfaces',
  srcs = glob(['**/*.java']),
  deps = [
    '//android_res/com/facebook/adinterfaces:res',
    '//android_res/com/facebook/common/strings:res',
    '//android_res/com/facebook/custom:res',
  ],
  visibility = [
    'PUBLIC',
  ],
)

project_config(
  src_target = ':adinterfaces',
)

